server:
  port: 8082

spring:
  application:
    name: blood-bank-api
  datasource:
    url: jdbc:mysql://localhost:3306/blood_bank_db?useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

logging:
  level:
    com.sena.bloodbank: DEBUG
